apiVersion:  batch/v1
kind: Job
metadata:
  name: batch-job2
spec:
  template:
    metadata:
      labels:
        app: batch-job2
    spec:
      restartPolicy: OnFailure
      containers:
      - name: sb-job
        image: 172.17.198.145:5000/mybatchjob:1.0
        command: ["ps"]
        args: ["aux"]
